### PR TITLE
using default namespace map to prevent false prefix.cc lookup

### PR DESCRIPTION
**Pull request by cKlee**

### CODE REVIEW

**Comment by cKlee** [comment]
@nichtich do you consider to merge this and make a new release?

**Comment by jhercher** [comment]
Installing aREF via 
 cpanm RDF::aREF
or 
 cpanm https://github.com/cKlee/RDF-aREF/archive/0.27.tar.gz
still fails with the error message below:

```
#   Failed test '"geo_Point"'
#   at t/objects.t line 32.
#     Structures begin differing at:
#          $got->[0] = 'http://www.opengis.net/ont/geosparql#Point'
#     $expected->[0] = 'http://www.w3.org/2003/01/geo/wgs84_pos#Point'
# Looks like you failed 1 test of 18.
t/objects.t ........ 
```

**Comment by jhercher** [comment]
currently, the install runs without errors for me. Thanks!

**Comment by cKlee** [comment]
@nichtich ping!

**Pull request merged**
